#+TITLE: Doom Emacs Configuration
#+AUTHOR: Rickard Natt och Dag
#+PROPERTY: header-args:emacs-lisp :tangle yes

* Introduction

Literate Doom Emacs configuration. This file is automatically tangled into
=config.el= on startup. Edit this file instead of =config.el= directly.

* Installation

** Emacs

Install =emacs-plus= which has worked the best for me of all versions listed in docs.

#+begin_src bash
brew tap d12frosted/emacs-plus
brew install emacs-plus
#+end_src

These are from the postinstall instructions of emacs-plus.

#+begin_src bash
# Copy apps
cp -r /opt/homebrew/opt/emacs-plus@30/Emacs.app /Applications/
cp -r "/opt/homebrew/opt/emacs-plus@30/Emacs Client.app" /Applications/

# Start daemon
brew services start d12frosted/emacs-plus/emacs-plus@30
#+end_src

** Install Doom

#+begin_src bash
# This is the default config and while take precendence if it exists
rm -rf ~/.emacs.d

# Install Doom
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
~/.config/emacs/bin/doom install
#+end_src

You might need to symlink the configuration from dotfiles to .doom.d

#+begin_src bash
ln -s ~/.dotfiles/doom ~/.doom.d
#+end_src

* Tangle on reload

This tangles the config.org to config.el on save.

#+begin_src emacs-lisp
(defun my/tangle-config ()
  ;; file-equal-p resolves symlinks
  (when (file-equal-p (buffer-file-name)
                      (expand-file-name "config.org" doom-user-dir))
    (org-babel-tangle)))

(add-hook 'after-save-hook #'my/tangle-config)
#+end_src


* Appearance

** Font

[[https://www.monolisa.dev/][MonoLisa]] as the primary monospace font.

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "MonoLisa" :size 12))
#+end_src

** Theme

A variation of my trusty [[https://github.com/folke/tokyonight.nvim][Tokyo Night]] by folke in nvim.

#+begin_src emacs-lisp
(setq doom-theme 'doom-tokyo-night)
#+end_src

** Line Numbers

Relative line numbers for easier vim-style navigation.

#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
#+end_src

** Cursor

Display a thin caret in insert mode when running in terminal.

#+begin_src emacs-lisp
(after! evil
  (unless (display-graphic-p)
    (require 'evil-terminal-cursor-changer)
    (evil-terminal-cursor-changer-activate)))
#+end_src

* Behaviour

** Misc

#+begin_src emacs-lisp
;; Skip confirm to exit message
(setq confirm-kill-emacs nil)

;; Calendars start on Monday
(setq calendar-week-start-day 1)

;; Move files to trash when deleting in dired
(setq delete-by-moving-to-trash t
      trash-directory "~/.Trash")
#+end_src

** Dired / Dirvish

Dirvish wraps dired in Doom. Hide file details by default in the explorer.

#+begin_src emacs-lisp
(after! dirvish
  (setq dirvish-hide-details t))
#+end_src

*** File handling

Start by marking a file with ~m~. From here you could also invert the selection by pressing ~t~ to mark everything that's _not_ this file.

With files selected, do:

- ~C~ to copy
- ~D~ to delete
- ~R~ to rename and/or move files
- ~Z~ to compress

You can also mark files for deletion by pressing ~d~ and then ~x~ to execute.

* Org Mode

** Links

- ~SPC m l l~ to insert/edit a link
- ~SPC m l t~ to toggle link displays

** Lists

- Similar to how bulleted lists work in other outliners, ~M-arrows~ moves items up/down or increase/decreases indentation
- Adding a new item of a similar kinds it done by ~C-RET~ in a list. I'm currently using the ~org-autolist~ to enable just doing ~RET~
- ~S-left~ and ~S-right~ toggle between different bullet styles for an entire list

** Dates

- Toggle a date between active and inactive press ~S-up~ or ~S-down~
- Using ~S-right~ or ~S-left~ to add or subtract a day in a date
- To add a scheduled or deadline date to a headline, use ~SPC m d s~ or ~SPC m d d~ respectively. This inserts an _active date_.

** Tasks

- Headline status can be toggled between TODO and DONE by pressing ~RET~ on the line in normal mode
- Add a TODO status to a headline with ~SPC m t t~ (or use ~SPC m t~ and select another status)

** Task lists [1/3]

- [X] This list has multiple items to complete
- [ ] By completing one we can indicate how many are done in the headline by adding ~[/]~
- [-] There's also a built-in syntax for nested items with partial completion
  - [X] Test 1
  - [ ] Test 2

** Priority

Tasks, or headlines in general can have a priority associated with them. This is added by pressing ~C-c ,~. This will automatically move to the closest headline above your current position and allow you to enter a priority.

** Directory & Agenda

#+begin_src emacs-lisp
(setq org-directory "~/.orgfiles/")
(setq org-agenda-files (directory-files-recursively org-directory "\\.org$"))
#+end_src

** Task Logging

Log a timestamp when a task is marked done.

#+begin_src emacs-lisp
(setq org-log-done 'time)
#+end_src

** Capture Templates

#+begin_src emacs-lisp
(setq org-default-notes-file (concat org-directory "notes.org"))

(setq org-capture-templates
      `(("t" "Task" entry
         (file+headline ,(concat org-directory "tasks.org") "Tasks")
         "* TODO %?\n%^t\n%a\n")))
#+end_src

* Notes (Denote)

[[https://protesilaos.com/emacs/denote][Denote]] for structured note-taking, stored alongside org files.

#+begin_src emacs-lisp
(use-package! denote
  :config
  (setq denote-directories
        (list (expand-file-name (concat org-directory "notes"))))
  (setq denote-dired-directories
        (list (expand-file-name (concat org-directory "notes"))))
  ;; This enables denote-dired-mode in notes, but I'm not seeing a difference
  (add-hook 'dired-mode-hook #'denote-dired-mode-in-directories))
#+end_src

** Keybindings

#+begin_src emacs-lisp
(map! :leader
      :prefix "n"
      :desc "New note"  "n" #'denote
      :desc "Link note" "l" #'denote-link)
#+end_src

* Export

Global author name used as a fallback when exporting org files.

#+begin_src emacs-lisp
(setq user-full-name "Rickard Natt och Dag")
#+end_src

* Languages

** Go

Use =goimports= (a superset of =gofmt=) to format and auto-import on save.

#+begin_src emacs-lisp
(after! go-mode
  (setq gofmt-command "goimports")
  (add-hook 'before-save-hook #'gofmt-before-save))
#+end_src

** TypeScript

Use Tree-sitter modes and configure LSP with both =ts-ls= and [[https://biomejs.dev/][Biome]].

#+begin_src emacs-lisp
;; Use TreeSitter modes for TypeScript/TSX files
(add-to-list 'auto-mode-alist '("\\.ts\\'" . typescript-ts-mode))
(add-to-list 'auto-mode-alist '("\\.tsx\\'" . tsx-ts-mode))

(after! lsp-mode
  ;; Map treesitter modes to LSP language IDs
  (add-to-list 'lsp-language-id-configuration '(typescript-ts-mode . "typescript"))
  (add-to-list 'lsp-language-id-configuration '(tsx-ts-mode . "typescriptreact"))

  (defun my/biome-find-root (file-name)
  "Walk up from FILE-NAME to find the nearest biome.json/biome.jsonc directory."
  (locate-dominating-file file-name
    (lambda (dir)
      (or (file-exists-p (expand-file-name "biome.json" dir))
          (file-exists-p (expand-file-name "biome.jsonc" dir))))))

(defun my/biome-project-root ()
  "Return the nearest biome.json directory for the current buffer, or nil."
  (when-let* ((buf-file (buffer-file-name)))
    (my/biome-find-root buf-file)))

  ;; Register Biome as an add-on LSP server (runs alongside ts-ls)
  (lsp-register-client
   (make-lsp-client
    :new-connection (lsp-stdio-connection
                     (lambda ()
                       ;; Prefer the local node_modules/.bin/biome over the global one,
                       ;; mirroring what nvim-lspconfig does
                       (let* ((root (my/biome-project-root))
                              (local-bin (and root
                                             (expand-file-name "node_modules/.bin/biome" root))))
                         (if (and local-bin (file-executable-p local-bin))
                             (list local-bin "lsp-proxy")
                           '("biome" "lsp-proxy")))))
      :activation-fn (lambda (file-name _mode)
                     ;; Only activate when the project actually uses Biome
                     (and (my/biome-find-root file-name) t))
    :multi-root nil
    :server-id 'biome
    :add-on? t))

  ;; Only allow these two clients
  (setq lsp-enabled-clients '(biome ts-ls)))

;; Start LSP in TreeSitter modes
(add-hook! '(typescript-ts-mode-hook tsx-ts-mode-hook) #'lsp!)

;; Exclude folders from lsp
(with-eval-after-load 'lsp-mode
  (add-to-list 'lsp-file-watch-ignored-directories "[/\\\\]node_modules\\'")
  (add-to-list 'lsp-file-watch-ignored-directories "[/\\\\]\\.git\\'")
  (add-to-list 'lsp-file-watch-ignored-directories "[/\\\\]dist\\'")
  (add-to-list 'lsp-file-watch-ignored-directories "[/\\\\]build\\'")
  (add-to-list 'lsp-file-watch-ignored-directories "[/\\\\]\\.next\\'")
  (add-to-list 'lsp-file-watch-ignored-directories "[/\\\\]\\.turbo\\'")
  (add-to-list 'lsp-file-watch-ignored-directories "[/\\\\]coverage\\'"))

;; Setup Biome formatting through Apheleia
(after! apheleia
  (setf (alist-get 'biome apheleia-formatters)
        ;; Command from conform.nvim. Using check --write also runs actions.
        '("biome" "check" "--write" "--stdin-file-path" filepath))
  (setf (alist-get 'tsx-ts-mode apheleia-mode-alist) '(biome))
  (setf (alist-get 'typescript-ts-mode apheleia-mode-alist) '(biome))
  (setf (alist-get 'js-ts-mode apheleia-mode-alist) '(biome))
  (setf (alist-get 'json-ts-mode apheleia-mode-alist) '(biome))
  (setf (alist-get 'json-mode apheleia-mode-alist) '(biome)))
#+end_src


** Treesitter

#+begin_src emacs-lisp
(use-package! treesit-auto
  :config
  (global-treesit-auto-mode))
#+end_src
